In [1]:
import tensorflow as tf

2024-03-17 17:06:54.407958: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-17 17:06:54.504751: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-17 17:06:55.418051: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
tf.constant([[3, 5, 7], [4, 6, 8]])[0]

2024-03-17 17:06:57.317079: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:f3:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-17 17:06:57.359362: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:f3:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-17 17:06:57.359396: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:f3:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-17 17:06:57.362842: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:f3:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-17 17:06:57.362900: I external/local_xla/xla/stream_executor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [3]:
tf.constant(
    [
        [[3, 5, 7], [4, 6, 8]],
        [[1, 2, 3], [4, 5, 6]],
    ]
)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[3, 5, 7],
        [4, 6, 8]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [4]:
x1 = tf.constant([2, 3, 4])
x2 = tf.stack([x1, x1])
x3 = tf.stack([x2, x2, x2, x2])
x3

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]]], dtype=int32)>

In [ ]:
x4 = tf.stack([x3, x3])

In [9]:
x = tf.constant(
    [
        [3, 5, 7],
        [2, 4, 6],
    ]
)
print(x)
x = tf.reshape(x, [3, 2])
x

tf.Tensor(
[[3 5 7]
 [2 4 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [7, 2],
       [4, 6]], dtype=int32)>

In [20]:
x = tf.Variable(2)
x.assign_add(3)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

In [23]:
w = tf.Variable(
    [
        [1.0],
        [2.0],
    ]
)
print(w)
x = tf.constant([[3.0, 4.0]])
print(x)
tf.matmul(w, x)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>
tf.Tensor([[3. 4.]], shape=(1, 2), dtype=float32)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>