In [1]:
import tensorflow as tf

2024-03-17 16:39:25.870379: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-17 16:39:25.977521: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-17 16:39:27.150527: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [12]:
tf.constant([[3,5,7],[4,6,8]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 7],
       [4, 6, 8]], dtype=int32)>

In [19]:
tf.constant([
    [[3,5,7],[4,6,8]],
    [[1,2,3],[4,5,6]],
             ])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[3, 5, 7],
        [4, 6, 8]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>